added some files
Catalin12/web-components pull request #1
Opened 2022-07-15 14:40 UTC by Catalin12

2022-07-15 15:37 UTC, danielursu requested changes

2022-07-15 15:37 UTC, danielursu commented on index.html
> +</html>
do this work? :))

2022-07-15 15:37 UTC, danielursu commented on index.html
> +</html>
move the head and body into html tag

2022-07-15 15:37 UTC, danielursu commented on word-counter.js
> +		let numberOfWords = this.shadowRoot.querySelector('p').innerText.split(" ").length;
```suggestion
		const numberOfWords = this.shadowRoot.querySelector('p').innerText.split(" ").length;
```

if you do not modify the variable it is better to declare it as const, not as let

2022-07-16 14:55 UTC, Catalin12 commented on index.html
> +</html>
lol :))

2022-07-18 09:07 UTC, danielursu requested changes

2022-07-18 09:07 UTC, danielursu commented on index.html
> +			<word-counter></word-counter>
send to word-counter the text via attribute "text"
```suggestion
			<p is="word-counter" text="Acesta este un text simplu. Cate cuvinte am?"></p>
```

2022-07-18 14:33 UTC, danielursu requested changes

2022-07-18 14:33 UTC, danielursu commented on word-counter.js
> +		<p class="word-counter">Acesta este un simplu text.</p>
get rid of this line. You do not need anymore

2022-07-18 14:37 UTC, danielursu approved these changes

2022-07-20 09:36 UTC, merged